spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DentalSurgeryDB
    username: user
    password: user123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update